---
# tasks file for ansible-role-flask
    - name:   Install and start flask web mysql-server
      pip: 
        name: 
          - flask 
          - flask-mysql 
    - name: deploy flask app 
      copy: 
        src: ./app.py 
        dest: /root/app.py 
    - name: start flask web server 
      shell: FLASK_APP=/root/app.py nohup flask run --host=0.0.0.0 &